name: nf_test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.8=1
  - trimmomatic=0.39=1
  - htstream=1.3.3
  - seqkit=0.16.0
  - pigz=2.6
  - python=3.7.1
  - pandas=1.2.0
  - seaborn=0.9.0
  - matplotlib=2.2.3
